<?php
$config = require __DIR__ . '/../config.php';
if (session_status() === PHP_SESSION_NONE) session_start();
function cfg($key = null) { global $config; return $key ? ($config[$key] ?? null) : $config; }
function h($s) { return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8'); }
function current_lang(): string { if (isset($_GET['lang']) && in_array($_GET['lang'], ['ru','kz','en'], true)) $_SESSION['app_lang'] = $_GET['lang']; return $_SESSION['app_lang'] ?? 'ru'; }
function dict(): array { static $cache=[]; $l=current_lang(); if(!isset($cache[$l])){ $f=__DIR__.'/../frontend_data/lang/'.$l.'.json'; $cache[$l]=file_exists($f)?(json_decode(file_get_contents($f),true)?:[]):[]; } return $cache[$l]; }
function tr($k){ $d=dict(); return $d[$k] ?? $k; }
function lang_url($lang) { $p=$_GET; $p['lang']=$lang; $u=strtok($_SERVER['REQUEST_URI'] ?? '', '?'); return $u.'?'.http_build_query($p); }
function make_pdo(string $dsn): PDO { $c=cfg(); return new PDO($dsn, $c['db_user'], $c['db_pass'], [PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC, PDO::ATTR_EMULATE_PREPARES=>false]); }
function candidate_dsns(bool $withDb=false): array { $c=cfg(); $db=$c['db_name']??'exam_analyzer_3'; $items=[]; $add=function($label,$dsn)use(&$items){ foreach($items as $i){ if($i['dsn']===$dsn) return; } $items[]=['label'=>$label,'dsn'=>$dsn];}; $host=$c['db_host']??'127.0.0.1'; $port=$c['db_port']??'3306'; $add("config {$host}:{$port}","mysql:host={$host};port={$port};charset=utf8mb4"); $add('127.0.0.1:3306','mysql:host=127.0.0.1;port=3306;charset=utf8mb4'); $add('localhost:3306','mysql:host=localhost;port=3306;charset=utf8mb4'); $add('127.0.0.1 без port','mysql:host=127.0.0.1;charset=utf8mb4'); $add('localhost без port','mysql:host=localhost;charset=utf8mb4'); $add('127.0.0.1:3307','mysql:host=127.0.0.1;port=3307;charset=utf8mb4'); $add('localhost:3307','mysql:host=localhost;port=3307;charset=utf8mb4'); if(!$withDb) return $items; return array_map(fn($x)=>['label'=>$x['label'].' + '.$db,'dsn'=>str_replace(';charset=utf8mb4',';dbname='.$db.';charset=utf8mb4',$x['dsn'])],$items); }
function server_pdo(): PDO { static $pdo=null; if($pdo) return $pdo; if(!extension_loaded('pdo_mysql')) die('pdo_mysql disabled'); $errs=[]; foreach(candidate_dsns(false) as $x){ try{$pdo=make_pdo($x['dsn']); $_SESSION['mysql_working_label']=$x['label']; return $pdo;}catch(Throwable $e){$errs[]=$x['label'].' — '.$e->getMessage();}} die('<pre>MySQL connection failed: '.h(implode("\n",$errs)).'</pre>'); }
function db(): PDO { static $pdo=null; if($pdo) return $pdo; $db=cfg('db_name') ?: 'exam_analyzer_3'; server_pdo()->exec("CREATE DATABASE IF NOT EXISTS `{$db}` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci"); $errs=[]; foreach(candidate_dsns(true) as $x){ try{$pdo=make_pdo($x['dsn']); return $pdo;}catch(Throwable $e){$errs[]=$x['label'].' — '.$e->getMessage();}} die('<pre>Database connection failed: '.h(implode("\n",$errs)).'</pre>'); }
function table_exists($name): bool { $st=db()->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = ?'); $st->execute([$name]); return ((int)$st->fetchColumn()) > 0; }
function one($sql,$params=[]){ $st=db()->prepare($sql); $st->execute($params); return $st->fetchColumn(); }
function rows($sql,$params=[]){ $st=db()->prepare($sql); $st->execute($params); return $st->fetchAll(); }
function install_if_needed(): void { static $done=false; if($done) return; $done=true; $need=false; foreach(['users','roles','imports_log','hier_questions','user_syllabuses'] as $t){ if(!table_exists($t)){ $need=true; break; } } if(!$need) return; $f=__DIR__.'/../frontend_data/sql/unified_database.sql'; if(!file_exists($f)) $f=__DIR__.'/../frontend_data/sql/exam_analyzer_full_install.sql'; if(!file_exists($f)) return; $sql=file_get_contents($f); $sql=preg_replace('/^\s*CREATE\s+DATABASE\s+IF\s+NOT\s+EXISTS\s+`?exam_analyzer_3`?.*?;\s*/im','',$sql); $sql=preg_replace('/^\s*USE\s+`?exam_analyzer_3`?;\s*/im','',$sql); foreach(preg_split('/;\s*(?:\r?\n|$)/',$sql) as $q){ $q=trim($q); if($q!==''){ try{ db()->exec($q); } catch(Throwable $e){ error_log('Install SQL: '.$e->getMessage().' SQL: '.mb_substr($q,0,200)); } } } }
function ensure_extra_tables(): void { $pdo=db(); if(!table_exists('user_sessions')) $pdo->exec("CREATE TABLE user_sessions (session_id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, token VARCHAR(255) NOT NULL, expires_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_user_id(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); }
function stat_count($table): int { if(!table_exists($table)) return 0; try{return (int)one('SELECT COUNT(*) FROM `'.str_replace('`','',$table).'`');}catch(Throwable $e){return 0;} }
function current_user(){ return $_SESSION['user'] ?? null; }
function require_login(){ if(!current_user()){ header('Location: /uams/login.php'); exit; } }
function role_options($selected){ $html=''; foreach(rows('SELECT role_id, role_name FROM roles ORDER BY role_id') as $r){ $sel=((int)$selected===(int)$r['role_id'])?' selected':''; $html.='<option value="'.h($r['role_id']).'"'.$sel.'>'.h($r['role_name']).'</option>'; } return $html; }
function page_header($title='', $active='dashboard'){ install_if_needed(); ensure_extra_tables(); $u=current_user(); $lang=current_lang(); $menu=[['dashboard','dashboard.php','dashboard'],['import','backend/import/import.php','import'],['analytics','analytics/index.php','analytics'],['questions','questions.php','questions'],['syllabus','syllabus.php','syllabus'],['users','users.php','users']]; ?>
<!doctype html><html lang="<?=h($lang)?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($title ?: tr('app_title'))?> — UAMS</title><link rel="stylesheet" href="/uams/assets/app.css"></head><body><div class="shell"><aside class="sidebar"><a class="brand" href="/uams/dashboard.php?lang=<?=h($lang)?>"><span class="brand-icon">U</span><span><b>UAMS</b><small><?=h(tr('app_title'))?></small></span></a><nav><?php foreach($menu as $m): ?><a class="nav-link <?=$active===$m[0]?'active':''?>" href="/uams/<?=$m[1]?>?lang=<?=h($lang)?>"><span>●</span><?=h(tr($m[2]))?></a><?php endforeach; ?></nav><div class="user-box"><span class="avatar"><?=h(mb_substr($u['full_name'] ?? 'U',0,1))?></span><span><b><?=h($u['full_name'] ?? '')?></b><small><?=h($u['login'] ?? '')?></small></span></div></aside><main class="main"><header class="topbar"><div><h1><?=h($title ?: tr($active))?></h1><p><?=h(tr('app_title'))?></p></div><div class="top-actions"><?php foreach(['ru'=>'RU','kz'=>'KZ','en'=>'EN'] as $k=>$v): ?><a class="lang <?=$lang===$k?'active':''?>" href="<?=h(lang_url($k))?>"><?=$v?></a><?php endforeach; ?><a class="btn ghost" href="/uams/logout.php"><?=h(tr('logout'))?></a></div></header><section class="content">
<?php }
function page_footer(){ ?></section></main></div></body></html><?php }
